server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportigo
    username: root
    password: Devansh2005@#
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

application:
  security:
    jwt:
      secret-key: b15f7819606774c89cbc1477c9dcbf149683af67ed2ca3e875718850c39330ce
      expiration: 86400000  # a day
      refresh-token:
        expiration: 604800000  # 7 days